version: '3'

services:
  mysql:
    container_name: mysql_ai_review
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "ai_review"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "review"
      MYSQL_PASSWORD: "review"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  ngrinder.controller:
    container_name: ngrinder_ai_review_controller
    image: ngrinder/controller:latest
    platform: linux/amd64
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
  ngrinder.agent:
    container_name: ngrinder_ai_review_agent
    platform: linux/amd64
    image: ngrinder/agent:latest
    command:
      - '127.0.0.1:9000'