spring:
  profiles:
    include: db
---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: false
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
---

