spring:
  profiles:
    include: db, secret
---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
server:
  tomcat:
    threads:
      max: 10
      min-spare: 10
    max-connections: 100
    accept-count: 10
    connection-timeout: 2000
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
---

