spring:
  profiles:
    active: local
    include: db, sentry
---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod